from pathlib import Path


ROOT_DIR = Path(__file__).parent
FILE_DIR = ROOT_DIR / 'icon.png'


# Size
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 22
SMALL_FONT_SIZE = 15
TEXT_MARGIN = 15


# Color
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
